# Generated by Django 5.0.8 on 2024-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('background_image', models.ImageField(upload_to='hero_backgrounds/')),
                ('icon', models.ImageField(upload_to='hero_icons/')),
            ],
        ),
    ]
